server:
  port: 8668

spring:
  application:
    name: kob-server-processor
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost_mysql:3306/kob?useUnicode=yes&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

debug: false

kob:
  cluster: kob
  core:
    zk_servers: localhost:2181
    zk_session_timeout: 10000
    zk_connection_timeout: 16000
  processor:
    task_push_threads: 36
    interval_min: 10
    waiting_task_scroll: 100