server:
  port: 8669

spring:
  application:
    name: kob-server-console
  freemarker:
    template-loader-path: classpath:/templates/
    suffix:
  mvc:
    static-path-pattern: /static/**
  datasource:
    username: root
    password: admin123
    url: jdbc:mysql://localhost:3306/kob?useUnicode=yes&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
# 控制台日志不看就注释此行
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

debug: false


kob-schedule:
  zk-connect-string: localhost:2181
  zk-prefix: kob
  mysql-prefix: kob

kob:
  cluster: kob
  mysql-prefix: kob
  zk-connect-string: localhost:2181
  core:
    zk_servers: localhost:2181
    zk_session_timeout: 10000
    zk_connection_timeout: 16000
  server:
    cluster: kob
    zk_servers: localhost:2181
    zk_session_timeout: 10000
    zk_connection_timeout: 16000
    task_push_threads: 36
    interval_min: 10
    waiting_task_scroll: 100